### ISSUE TITLE
decouple control on identifier from what is being identified 

### ISSUE THREAD

**Issue by jeborsel** [oSoc20/bit-of-trust#2]

**Comment by timplication** [comment]
This is already the case, public keys are not identifiers. They are shards of a trust relationship that you hand out to somebody who is a member of the relationship, but they are owned by a specific person. You can think of it like having a share in a company, except now you have a share in a trust relationship. 

We are using public keys for this in the current version because we do not want people to be able to fake these 'shares', but this doesn't mean that we don't want to think about mechanisms for transferring the ownership of these 'shares' or how we have recently taken to calling them 'trust shards'.
